package generation

import (
	"bytes"
	"fmt"
	"os"
	"strings"
	"time"

	"github.com/dave/jennifer/jen"
	"github.com/efritz/go-mockgen/specs"
)

func generateContent(allSpecs specs.Specs, pkgName, prefix string) (string, error) {
	file := jen.NewFile(pkgName)
	file.HeaderComment("Code generated by github.com/efritz/go-mockgen; DO NOT EDIT.")
	file.HeaderComment("This file was generated by robots at")
	file.HeaderComment(time.Now().Format(time.RFC3339))
	file.HeaderComment("using the command")
	file.HeaderComment(fmt.Sprintf("$ %s", strings.Join(os.Args, " ")))

	for _, name := range allSpecs.Names() {
		spec := allSpecs[strings.ToLower(name)]

		generator := newInterfaceGenerator(
			file,
			spec.Spec.TitleName,
			prefix,
			spec,
		)

		generator.generate()
	}

	buffer := &bytes.Buffer{}
	if err := file.Render(buffer); err != nil {
		return "", err
	}

	return buffer.String(), nil
}
