name: test
on:
  push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.18'
      
      - name: Generate
        run: go generate ./...
      - name: Test
        run: go test -race -v ./...
